set(DIR "${OUT}/c-project")
file(COPY "${ROOT}/tests/c_project/Declarations.zsharp" DESTINATION "${DIR}")
set(ENV{ZSHARP_SKIP_UPDATE_CHECK} "1")
function(run_ok)
 execute_process(COMMAND "${BIN}" ${ARGN} WORKING_DIRECTORY "${DIR}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
 if(NOT status EQUAL 0)
  message(FATAL_ERROR "C declarations failed: ${status}\n${output}\n${error}")
 endif()
 set(LAST_OUTPUT "${output}" PARENT_SCOPE)
endfunction()
run_ok(run Declarations.zsharp)
foreach(expected "CONFIGURATION BOUND" "FUNCTION OPTION BOUND" "FUNCTION DURATION BOUND" "OVERLOADS: 5, 5" "START FINISHED" "DECLARATION CALLBACK: 7" "SERVICE SHUTDOWN")
 if(NOT LAST_OUTPUT MATCHES "${expected}")
  message(FATAL_ERROR "Missing ${expected}: ${LAST_OUTPUT}")
 endif()
endforeach()
if(NOT LAST_OUTPUT MATCHES "START FINISHED[\r\n]+DECLARATION CALLBACK: 7")
 message(FATAL_ERROR "Callback did not run after Start returned: ${LAST_OUTPUT}")
endif()
run_ok(compile Declarations.zsharp -o Declarations.zbc)
run_ok(run-bytecode Declarations.zbc)
if(NOT LAST_OUTPUT MATCHES "FUNCTION OPTION BOUND")
 message(FATAL_ERROR "Bytecoded function options did not initialize: ${LAST_OUTPUT}")
endif()
if(NOT LAST_OUTPUT MATCHES "DECLARATION CALLBACK: 7")
 message(FATAL_ERROR "Bytecoded declaration did not dispatch: ${LAST_OUTPUT}")
endif()
file(READ "${ROOT}/tests/c_project/Declarations.zsharp" valid)
foreach(duration "5ms" "5000ms" "0.5s" "0ms")
 string(REPLACE "Fixture.Duration(5s)" "Fixture.Duration(${duration})" duration_source "${valid}")
 file(WRITE "${DIR}/DurationOption.zsharp" "${duration_source}")
 run_ok(check DurationOption.zsharp)
endforeach()
file(REMOVE "${DIR}/DurationOption.zsharp")
foreach(duration "5" "5m" "-5s" "5s, 5s" "\"5s\"")
 string(REPLACE "Fixture.Duration(5s)" "Fixture.Duration(${duration})" duration_source "${valid}")
 file(WRITE "${DIR}/DurationOption.zsharp" "${duration_source}")
 execute_process(COMMAND "${BIN}" check DurationOption.zsharp WORKING_DIRECTORY "${DIR}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
 if(status EQUAL 0)
  message(FATAL_ERROR "Invalid function duration ${duration} was accepted")
 endif()
endforeach()
file(REMOVE "${DIR}/DurationOption.zsharp")
foreach(case empty number late)
 if(case STREQUAL "empty")
  string(REPLACE "Fixture.Option(\"?\", \"!\", \"*\")" "Fixture.Option()" invalid "${valid}")
 elseif(case STREQUAL "number")
  string(REPLACE "Fixture.Option(\"?\", \"!\", \"*\")" "Fixture.Option(42)" invalid "${valid}")
 else()
  string(REPLACE "Fixture.Option(\"?\", \"!\", \"*\"):" "Print(\"before option\"):\n Fixture.Option(\"?\", \"!\", \"*\"):" invalid "${valid}")
 endif()
 file(WRITE "${DIR}/InvalidOption.zsharp" "${invalid}")
 execute_process(COMMAND "${BIN}" check InvalidOption.zsharp WORKING_DIRECTORY "${DIR}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
 if(status EQUAL 0 OR NOT error MATCHES "function option")
  message(FATAL_ERROR "Invalid option ${case} was not clearly rejected: ${output}\n${error}")
 endif()
 file(REMOVE "${DIR}/InvalidOption.zsharp")
endforeach()
