set(project "${OUT}/game-instance-validation")
file(MAKE_DIRECTORY "${project}")
file(COPY "${ROOT}/tests/game_instances/" DESTINATION "${project}")
execute_process(COMMAND "${BIN}" package game "${project}" InstanceTest
 RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
 message(FATAL_ERROR "Instance packaging failed: ${output} ${error}")
endif()
if(WIN32)
 file(WRITE "${project}/input.txt" "n\n")
 execute_process(COMMAND "${CMAKE_COMMAND}" -E env ZSHARP_GAME_AUTOCLOSE_MS=10000 "${BIN}" run "${project}/Packages/InstanceTest.zgame"
  INPUT_FILE "${project}/input.txt" TIMEOUT 20 RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
 if(NOT result EQUAL 0 OR output MATCHES "FAIL" OR NOT output MATCHES "Scene instance runtime passed")
  message(FATAL_ERROR "Instance runtime failed: ${result} ${output} ${error}")
 endif()
endif()
file(READ "${project}/Floor1.zscene" scene)
string(REPLACE "\"instanceId\": \"RightDoor\"" "\"instanceId\": \"LeftDoor\"" duplicate "${scene}")
file(WRITE "${project}/Floor1.zscene" "${duplicate}")
execute_process(COMMAND "${BIN}" package game "${project}" BadDuplicate RESULT_VARIABLE result ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT error MATCHES "duplicate scene instance")
 message(FATAL_ERROR "Duplicate instance accepted: ${error}")
endif()
string(REPLACE "\"instanceId\": \"RightDoor\"" "\"instanceId\": \"bad.identifier\"" invalid "${scene}")
file(WRITE "${project}/Floor1.zscene" "${invalid}")
execute_process(COMMAND "${BIN}" package game "${project}" BadIdentifier RESULT_VARIABLE result ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT error MATCHES "invalid instanceId")
 message(FATAL_ERROR "Invalid instance accepted: ${error}")
endif()
string(REPLACE "\"name\": \"Right Door\"" "\"name\": \"LeftDoor\"" ambiguous "${scene}")
string(REPLACE ", \"instanceId\": \"RightDoor\"" "" ambiguous "${ambiguous}")
file(WRITE "${project}/Floor1.zscene" "${ambiguous}")
execute_process(COMMAND "${BIN}" package game "${project}" BadAmbiguous RESULT_VARIABLE result ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT error MATCHES "ambiguous scene instance")
 message(FATAL_ERROR "Ambiguous reference accepted: ${error}")
endif()
file(WRITE "${project}/Floor1.zscene" "${scene}")
file(READ "${project}/project.zsettings" settings)
string(REPLACE "ZSharp: [1.2.1.0]:" "ZSharp: [1.2.0.1]:" legacy "${settings}")
file(WRITE "${project}/project.zsettings" "${legacy}")
execute_process(COMMAND "${BIN}" package game "${project}" BadVersion RESULT_VARIABLE result ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT error MATCHES "instanceId requires ZSharp")
 message(FATAL_ERROR "instanceId version gate failed: ${error}")
endif()
file(WRITE "${project}/project.zsettings" "${settings}")
