set(project "${OUT}/game-button-validation")
file(MAKE_DIRECTORY "${project}")
file(COPY "${ROOT}/tests/game_package/" DESTINATION "${project}")
file(READ "${project}/Button.zobject" original)
function(package_button expect_success expected_error)
 execute_process(COMMAND "${BIN}" package game "${project}" ButtonTest
                 RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
 if(expect_success AND NOT result EQUAL 0)
  message(FATAL_ERROR "Button package failed: ${error}")
 elseif(NOT expect_success AND (result EQUAL 0 OR NOT error MATCHES "${expected_error}"))
  message(FATAL_ERROR "Invalid button accepted or wrong error: ${error}")
 endif()
endfunction()
package_button(TRUE "")
string(REPLACE "left:" "right:" right_only "${original}")
file(WRITE "${project}/Button.zobject" "${right_only}")
package_button(TRUE "")
string(REPLACE "left: \"Main:Game:ButtonClick\":" "left: \"Main:Game:ButtonClick\":\n right: \"Main:Game:ButtonClick\":" both "${original}")
file(WRITE "${project}/Button.zobject" "${both}")
package_button(TRUE "")
string(REGEX REPLACE "event\\([^)]*\\)" "" missing "${original}")
file(WRITE "${project}/Button.zobject" "${missing}")
package_button(FALSE "requires an event")
string(REGEX REPLACE "event\\([^)]*\\)" "event()" empty "${original}")
file(WRITE "${project}/Button.zobject" "${empty}")
package_button(FALSE "at least one click action")
string(REPLACE "Main:Game:ButtonClick" "bad-target" invalid "${original}")
file(WRITE "${project}/Button.zobject" "${invalid}")
package_button(FALSE "click target must be")
file(WRITE "${project}/Button.zobject" "${original}")
file(READ "${project}/Main.zsharp" main_source)
file(READ "${project}/project.zsettings" settings)
string(REPLACE "ZSharp: [1.0.2.1]:" "ZSharp: [1.2.1.0]:" settings "${settings}")
file(WRITE "${project}/project.zsettings" "${settings}")
string(REPLACE "Print(\"game start ran\"):" "Print(\"game start ran\"):\n  Application.Quit:\n  Print(\"UNREACHABLE AFTER QUIT\"):" quit_source "${main_source}")
file(WRITE "${project}/Main.zsharp" "${quit_source}")
package_button(TRUE "")
if(WIN32)
 file(WRITE "${project}/quit-input.txt" "n\n")
 execute_process(COMMAND "${CMAKE_COMMAND}" -E env ZSHARP_GAME_RASTER_TEST=1 "${BIN}" run "${project}/Packages/ButtonTest.zgame"
  INPUT_FILE "${project}/quit-input.txt"
  TIMEOUT 15 RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
 if(NOT result EQUAL 0 OR NOT output MATCHES "game shutdown ran: started" OR output MATCHES "UNREACHABLE AFTER QUIT")
  message(FATAL_ERROR "Application.Quit lifecycle failed: ${result} ${output} ${error}")
 endif()
endif()
