set(project "${OUT}/file-search-tests")
file(MAKE_DIRECTORY "${project}/Assets/Nested" "${project}/build")
file(WRITE "${project}/project.zsettings" "zsharp = type.settings\nProject: \"File Search\":\nPID: \"file_search\":\nVersion: [1.0.0.0]:\nAuthors: [\"Tests\"]:\nDescription: \"Tests\":\nZSharp: [1.2.1.0]:\nDependencies (): \n")
file(WRITE "${project}/Assets/a.PNG" "a")
file(WRITE "${project}/Assets/Nested/b.png" "b")
file(WRITE "${project}/build/c.png" "c")
file(WRITE "${project}/Assets/no.txt" "no")
set(source [=[zsharp = type.script
noticed room Main[] (
 noticed brain Start[] (
  text() Files = File.searchExtension(".PnG"):
  Print(Files.Length):
  Print(Files[0]):
  Print(Files[1]):
  Print(Files[2]):
  text First = File.searchExtension(".png")[0]:
  Print(First):
  text() Empty = File.searchExtension(".missing"):
  Print(Empty.Length):
 )
)
]=])
file(WRITE "${project}/Main.zsharp" "${source}")
function(check_output command)
 execute_process(COMMAND "${BIN}" ${command} "${ARGN}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
 string(REPLACE "\r" "" output "${output}")
 if(NOT result EQUAL 0 OR NOT output STREQUAL "3\nAssets/Nested/b.png\nAssets/a.PNG\nbuild/c.png\nAssets/Nested/b.png\n0\n")
  message(FATAL_ERROR "Search result mismatch: ${result} ${output} ${error}")
 endif()
endfunction()
check_output(run "${project}/Main.zsharp")
execute_process(COMMAND "${BIN}" compile "${project}/Main.zsharp" -o "${project}/Main.zbc" RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 0)
 message(FATAL_ERROR "Search bytecode compile failed: ${error}")
endif()
check_output(run-bytecode "${project}/Main.zbc")
string(REPLACE "text() Files = File.searchExtension(\".PnG\")" "text() Files = \"wrong\"" invalid "${source}")
file(WRITE "${project}/Main.zsharp" "${invalid}")
execute_process(COMMAND "${BIN}" run "${project}/Main.zsharp" RESULT_VARIABLE result ERROR_VARIABLE error TIMEOUT 15)
if(result EQUAL 0 OR NOT error MATCHES "requires a text array")
 message(FATAL_ERROR "Local text array type check failed: ${error}")
endif()
string(REPLACE "Files[0]" "Files[3]" invalid "${source}")
file(WRITE "${project}/Main.zsharp" "${invalid}")
execute_process(COMMAND "${BIN}" run "${project}/Main.zsharp" RESULT_VARIABLE result ERROR_VARIABLE error TIMEOUT 15)
if(result EQUAL 0 OR NOT error MATCHES "index 3")
 message(FATAL_ERROR "Zero-based search array bounds failed: ${error}")
endif()
foreach(extension "" "png" "../png" ".*")
 string(REPLACE ".PnG" "${extension}" invalid "${source}")
 file(WRITE "${project}/Main.zsharp" "${invalid}")
 execute_process(COMMAND "${BIN}" run "${project}/Main.zsharp" RESULT_VARIABLE result ERROR_VARIABLE error TIMEOUT 15)
 if(result EQUAL 0 OR NOT error MATCHES "requires an extension")
  message(FATAL_ERROR "Invalid extension accepted: '${extension}': ${error}")
 endif()
endforeach()
string(REPLACE ".PnG" ".missing" invalid "${source}")
file(WRITE "${project}/Main.zsharp" "${invalid}")
execute_process(COMMAND "${BIN}" run "${project}/Main.zsharp" RESULT_VARIABLE result ERROR_VARIABLE error TIMEOUT 15)
if(result EQUAL 0 OR NOT error MATCHES "index")
 message(FATAL_ERROR "Empty result indexing accepted: ${error}")
endif()
file(WRITE "${project}/Main.zsharp" "${source}")
file(READ "${project}/project.zsettings" settings)
string(REPLACE "1.2.1.0" "1.2.0.1" settings "${settings}")
file(WRITE "${project}/project.zsettings" "${settings}")
execute_process(COMMAND "${BIN}" run "${project}/Main.zsharp" RESULT_VARIABLE result ERROR_VARIABLE error TIMEOUT 15)
if(result EQUAL 0 OR NOT error MATCHES "1.2.1.0")
 message(FATAL_ERROR "Version gate failed: ${error}")
endif()
