set(project "${OUT}/game-button-validation")
file(MAKE_DIRECTORY "${project}")
file(COPY "${ROOT}/tests/game_package/" DESTINATION "${project}")
file(READ "${project}/Button.zobject" original)
function(package_button expect_success expected_error)
 execute_process(COMMAND "${BIN}" package game "${project}" ButtonTest
                 RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
 if(expect_success AND NOT result EQUAL 0)
  message(FATAL_ERROR "Button package failed: ${error}")
 elseif(NOT expect_success AND (result EQUAL 0 OR NOT error MATCHES "${expected_error}"))
  message(FATAL_ERROR "Invalid button accepted or wrong error: ${error}")
 endif()
endfunction()
package_button(TRUE "")
string(REPLACE "left:" "right:" right_only "${original}")
file(WRITE "${project}/Button.zobject" "${right_only}")
package_button(TRUE "")
string(REPLACE "left: \"Main:Game:ButtonClick\":" "left: \"Main:Game:ButtonClick\":\n right: \"Main:Game:ButtonClick\":" both "${original}")
file(WRITE "${project}/Button.zobject" "${both}")
package_button(TRUE "")
string(REGEX REPLACE "event\\([^)]*\\)" "" missing "${original}")
file(WRITE "${project}/Button.zobject" "${missing}")
package_button(FALSE "requires an event")
string(REGEX REPLACE "event\\([^)]*\\)" "event()" empty "${original}")
file(WRITE "${project}/Button.zobject" "${empty}")
package_button(FALSE "at least one click action")
string(REPLACE "Main:Game:ButtonClick" "bad-target" invalid "${original}")
file(WRITE "${project}/Button.zobject" "${invalid}")
package_button(FALSE "click target must be")
