set(project "${OUT}/package-ignore-fixture")
file(MAKE_DIRECTORY "${project}")
file(COPY "${ROOT}/tests/game_instances/" DESTINATION "${project}")
set(ENV{ZSHARP_SKIP_UPDATE_CHECK} "1")
file(WRITE "${project}/.env" "DO_NOT_PACKAGE_TEST_SECRET")
file(WRITE "${project}/Examples/Broken.zsharp" "intentionally invalid source")
file(WRITE "${project}/C/debug.obj" "object file")
file(WRITE "${project}/Assets/keep.txt" "included")
file(WRITE "${project}/Assets/drop.txt" "excluded")
file(WRITE "${project}/Assets/deep/data.cache" "excluded")
file(WRITE "${project}/Assets/important.cache" "included exception")
file(WRITE "${project}/root-only.txt" "excluded root")
file(WRITE "${project}/Assets/root-only.txt" "included nested")
file(WRITE "${project}/#literal" "excluded")
file(WRITE "${project}/.zignore" "# comment\n\n.env\n/Examples/\n*.obj\nAssets/*.txt\n!Assets/keep.txt\n!Assets/root-only.txt\n**/*.cache\n!Assets/important.cache\n/root-only.txt\n\\#literal\n")
function(run_ok)
 execute_process(COMMAND "${BIN}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
 if(NOT status EQUAL 0)
  message(FATAL_ERROR "Packaging .zignore failed: ${output}\n${error}")
 endif()
endfunction()
function(check_binary path)
 file(READ "${path}" data HEX)
 foreach(excluded ".env" "DO_NOT_PACKAGE_TEST_SECRET" "Examples/Broken.zsharp" "C/debug.obj" "Assets/drop.txt" "Assets/deep/data.cache" ".zignore" "#literal")
  string(HEX "${excluded}" needle)
  string(FIND "${data}" "${needle}" found)
  if(NOT found EQUAL -1)
   message(FATAL_ERROR "Excluded content ${excluded} leaked into ${path}")
  endif()
 endforeach()
endfunction()
run_ok(package game "${project}" Ignored --unbytecode)
check_binary("${project}/Packages/Ignored.zgame")
run_ok(package pack "${project}" Sources)
foreach(archive "Ignored-unbytecoded.zgame" "Sources.zpackage")
 set(extracted "${OUT}/package-ignore-inspection/${archive}")
 file(ARCHIVE_EXTRACT INPUT "${project}/Packages/${archive}" DESTINATION "${extracted}" TOUCH)
 foreach(excluded ".env" ".zignore" "Examples/Broken.zsharp" "C/debug.obj" "Assets/drop.txt" "Assets/deep/data.cache" "root-only.txt" "#literal")
  if(EXISTS "${extracted}/${excluded}")
   message(FATAL_ERROR "Excluded ${excluded} is in ${archive}")
  endif()
 endforeach()
 foreach(included "project.zsettings" "Assets/keep.txt" "Assets/root-only.txt" "Assets/important.cache")
  if(NOT EXISTS "${extracted}/${included}")
   message(FATAL_ERROR "Required included file ${included} missing from ${archive}")
  endif()
 endforeach()
endforeach()
# Native app packages use the same collector, without launching any executable.
set(app "${OUT}/package-ignore-native-app")
file(MAKE_DIRECTORY "${app}")
file(WRITE "${app}/project.zsettings" "zsharp = type.settings\nProject: \"Ignore App\":\nPID: \"ignore_app\":\nVersion: [1.0.0.0]:\nAuthors: [\"Tests\"]:\nDescription: \"Test\":\nZSharp: [1.2.1.0]:\nDependencies ():\nNative[JSON] ([{\"platform\":\"windows-x86_64\",\"start\":\"runner.exe\"}]):\n")
file(WRITE "${app}/runner.exe" "not launched")
file(WRITE "${app}/.env" "DO_NOT_PACKAGE_TEST_SECRET")
file(WRITE "${app}/.zignore" ".env\n")
run_ok(package app "${app}" App)
check_binary("${app}/Packages/App.zapp")
foreach(required "project.zsettings" "runner.exe")
 file(WRITE "${app}/.zignore" "${required}\n")
 execute_process(COMMAND "${BIN}" package app "${app}" Invalid RESULT_VARIABLE status ERROR_VARIABLE error)
 if(status EQUAL 0 OR NOT error MATCHES "excluded by .zignore")
  message(FATAL_ERROR "Ignoring required ${required} did not fail clearly: ${error}")
 endif()
endforeach()
