set(DIR "${OUT}/callback-validation")
file(MAKE_DIRECTORY "${DIR}")
file(COPY "${ROOT}/tests/callbacks/" DESTINATION "${DIR}")
set(ENV{ZSHARP_SKIP_UPDATE_CHECK} "1")
function(run_ok label)
 execute_process(COMMAND "${BIN}" ${ARGN} WORKING_DIRECTORY "${DIR}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
 if(NOT status EQUAL 0)
  message(FATAL_ERROR "${label}: ${status}\n${output}\n${error}")
 endif()
 set(LAST_OUTPUT "${output}" PARENT_SCOPE)
endfunction()
function(run_bad label expected)
 execute_process(COMMAND "${BIN}" ${ARGN} WORKING_DIRECTORY "${DIR}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
 if(status EQUAL 0 OR NOT "${output}\n${error}" MATCHES "${expected}")
  message(FATAL_ERROR "${label}: ${status}\n${output}\n${error}")
 endif()
endfunction()
run_ok(source run Main.zsharp)
foreach(expected "room text: 10" "room function: 11" "local text: 12"
 "local function: 13" "text parameter: 14" "function parameter: 15"
 "room reference copy: 18" "Outcome: 21"
 "reassigned: 16" "17" "29" "CALLBACK TESTS PASSED")
 if(NOT LAST_OUTPUT MATCHES "${expected}")
  message(FATAL_ERROR "Missing ${expected}: ${LAST_OUTPUT}")
 endif()
endforeach()
run_ok(compile compile Main.zsharp -o Callbacks.zbc)
run_ok(bytecode run-bytecode Callbacks.zbc)
if(NOT LAST_OUTPUT MATCHES "CALLBACK TESTS PASSED")
 message(FATAL_ERROR "Bytecode callback execution failed: ${LAST_OUTPUT}")
endif()
file(READ "${DIR}/Main.zsharp" ORIGINAL)
function(case_source body)
 file(WRITE "${DIR}/Negative.zsharp" "zsharp = type.script\nnoticed room Main[] (\n noticed brain Start[] (\n ${body}\n )\n)\n")
endfunction()
case_source("text Target = \"Targets:Handlers:Ping\": Function.call(Target):")
run_bad(import "without importing" run Negative.zsharp)
case_source("text Target = \"../Targets:Handlers:Ping\": Function.call(Target):")
run_bad(path "invalid callback target" run Negative.zsharp)
case_source("text Target = \"\": Function.call(Target):")
run_bad(empty "invalid callback target" run Negative.zsharp)
case_source("number Target = 2: Function.call(Target):")
run_bad(type "requires text or a function reference" run Negative.zsharp)
case_source("text TextRef = \"Targets:Handlers:Ping\": function Typed = TextRef:")
run_bad(localtype "requires a function value" run Negative.zsharp)
case_source("Function.call(Missing):")
run_bad(undefined "no value named 'Missing'" compile Negative.zsharp -o Negative.zbc)
file(WRITE "${DIR}/Negative.zsharp" "zsharp = type.script\nnoticed room Main[] (\n import callback_tests.Targets():\n noticed brain Start[] (\n text Target = \"Targets:Handlers:Private\": Function.call(Target):\n )\n)\n")
run_bad(visibility "silent outside" run Negative.zsharp)
file(READ "${DIR}/Negative.zsharp" NEGATIVE)
string(REPLACE "Private" "Say" NEGATIVE "${NEGATIVE}")
file(WRITE "${DIR}/Negative.zsharp" "${NEGATIVE}")
run_bad(arity "expects 2 argument" run Negative.zsharp)
string(REPLACE "Function.call(Target):" "Function.call(Target [10, 20]):" NEGATIVE "${NEGATIVE}")
file(WRITE "${DIR}/Negative.zsharp" "${NEGATIVE}")
run_bad(argumenttype "wrong type" run Negative.zsharp)
file(WRITE "${DIR}/Negative.zsharp" "zsharp = type.script\nnoticed room Main[] (\n import callback_tests.Targets():\n noticed function Ref = Targets:Handlers:Private:\n noticed brain Start[] ()\n)\n")
run_bad(privatebinding "not visible" compile Negative.zsharp -o Negative.zbc)
file(WRITE "${DIR}/Negative.zsharp" "zsharp = type.script\nnoticed room Main[] (\n import callback_tests.Targets():\n noticed function Ref = Targets:Handlers:Missing:\n noticed brain Start[] ()\n)\n")
run_bad(binding "could not resolve" compile Negative.zsharp -o Negative.zbc)
file(WRITE "${DIR}/Negative.zsharp" "zsharp = type.script\nnoticed room Main[] (\n noticed brain Start[] (\n text Target = \"Negative:Main:Forward\": Function.call(Negative:Main:Forward [Target]):\n )\n noticed brain Forward[function Target] (Function.call(Target):)\n)\n")
run_bad(paramtype "wrong type" run Negative.zsharp)
file(WRITE "${DIR}/Negative.zsharp" "zsharp = type.script\nnoticed room Main[] (\n noticed brain Start[] (\n text Target = \"Negative:Main:Forward\": Function.call(Target [Target]):\n )\n noticed brain Forward[text Target] (Function.call(Target [Target]):)\n)\n")
run_bad(depth "maximum call depth" run Negative.zsharp)
file(REMOVE "${DIR}/Negative.zsharp")
file(READ "${DIR}/project.zsettings" SETTINGS)
string(REPLACE "[1.2.1.0]" "[1.2.0.1]" SETTINGS "${SETTINGS}")
file(WRITE "${DIR}/project.zsettings" "${SETTINGS}")
run_bad(version "require ZSharp.*1.2.1.0" compile Main.zsharp -o Old.zbc)
