if(NOT DEFINED BIN OR NOT DEFINED ROOT OR NOT DEFINED OUT)
    message(FATAL_ERROR "missing dependency test paths")
endif()
set(base "${OUT}/source-dependency-tests")
file(REMOVE_RECURSE "${base}")
file(MAKE_DIRECTORY "${base}/library" "${base}/consumer/Dependencies" "${base}/library/Lua")
set(ENV{ZSHARP_SKIP_UPDATE_CHECK} 1)
function(settings path pid dependencies)
    file(WRITE "${path}/project.zsettings" "zsharp = type.settings\nProject: \"Dependency Test\":\nPID: \"${pid}\":\nVersion: [1.0.0.0]:\nAuthors: [\"Tests\"]:\nDescription: \"Tests\":\nZSharp: [1.2.1.0]:\nDependencies (\n${dependencies}\n):\n")
endfunction()
function(command)
    execute_process(COMMAND "${BIN}" ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 25)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "dependency test command failed (${result}): ${ARGN}\n${output}\n${error}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
    set(last_error "${error}" PARENT_SCOPE)
endfunction()
settings("${base}/library" "test_library" "")
settings("${base}/consumer" "test_consumer" " test_library:1.0.0.0:")
file(WRITE "${base}/library/Main.zsharp" "zsharp = type.script\nnoticed room Library[] (\n import test_library.Helper():\n noticed text Message = \"initial\":\n noticed brain Start[] ( Print(\"DEPENDENCY START MUST NOT AUTORUN\"): )\n noticed brain Hello[text Name] (\n Print(\"DEPENDENCY HELLO \" + Name):\n Function.call(Helper:Helper:Ping):\n text Content = File.read(\"data.txt\"):\n Print(Content):\n )\n)\n")
file(WRITE "${base}/library/Helper.zsharp" "zsharp = type.script\nnoticed room Helper[] ( noticed brain Ping[] ( Print(\"DEPENDENCY INTERNAL CALL\"): ) )\n")
file(WRITE "${base}/library/data.txt" "DEPENDENCY RELATIVE FILE")
file(WRITE "${base}/library/Lua/Values.lua" "function answer(x) return x+7 end\n")
file(WRITE "${base}/library/stale.zbc" "must not be packaged")
command(package pack "${base}/library" Library)
file(COPY_FILE "${base}/library/Packages/Library.zpackage" "${base}/consumer/Dependencies/arbitrary-name.zpackage")
file(WRITE "${base}/consumer/Main.zsharp" "zsharp = type.script\nnoticed room Main[] (\n import test_library.Main():\n import lua:test_library.Lua.Values():\n noticed brain Start[] (\n Function.call(test_library:Main:Library:Hello [\"BOT\"]):\n text.set.test_library.Main.Library.Message = \"DEPENDENCY VARIABLE UPDATED\":\n Print(test_library.Main.Library.Message):\n number Answer = Function.call(lua:test_library.Lua.Values:answer [35]):\n Print(Answer):\n text Callback = \"lua:test_library.Lua.Values:answer\":\n number Next = Function.call(Callback [36]):\n Print(Next):\n )\n)\n")
command(run "${base}/consumer/Main.zsharp")
if(NOT last_output MATCHES "DEPENDENCY HELLO BOT" OR NOT last_output MATCHES "DEPENDENCY INTERNAL CALL" OR
   NOT last_output MATCHES "DEPENDENCY RELATIVE FILE" OR NOT last_output MATCHES "42" OR
   NOT last_output MATCHES "DEPENDENCY VARIABLE UPDATED" OR NOT last_output MATCHES "43" OR
   last_output MATCHES "MUST NOT AUTORUN" OR last_error MATCHES "downloading dependency")
    message(FATAL_ERROR "local source dependency execution failed: ${last_output}\n${last_error}")
endif()
if(NOT EXISTS "${base}/consumer/Dependencies/test_library/1.0.0.0/Main.zsharp" OR
   EXISTS "${base}/consumer/Dependencies/test_library/1.0.0.0/stale.zbc")
    message(FATAL_ERROR "source dependency was not installed correctly")
endif()
command(run "${base}/consumer/Main.zsharp")
if(last_error MATCHES "downloading dependency")
    message(FATAL_ERROR "cached dependency unexpectedly downloaded")
endif()
command(compile "${base}/consumer/Main.zsharp" -o "${base}/consumer/Main.zbc")
command(run-bytecode "${base}/consumer/Main.zbc")
if(NOT last_output MATCHES "DEPENDENCY HELLO BOT" OR NOT last_output MATCHES "42")
    message(FATAL_ERROR "bytecode dependency execution failed: ${last_output}")
endif()
execute_process(COMMAND "${BIN}" package pack "${base}/library" Invalid --unbytecode
    RESULT_VARIABLE result ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT error MATCHES "always source-only")
    message(FATAL_ERROR "pack accepted --unbytecode")
endif()
file(COPY_FILE "${base}/library/Packages/Library.zpackage" "${base}/consumer/Dependencies/duplicate.zpackage")
execute_process(COMMAND "${BIN}" run "${base}/consumer/Main.zsharp" RESULT_VARIABLE result ERROR_VARIABLE error TIMEOUT 10)
if(result EQUAL 0 OR NOT error MATCHES "multiple .zpackage")
    message(FATAL_ERROR "ambiguous dependency was accepted: ${error}")
endif()
file(REMOVE "${base}/consumer/Dependencies/duplicate.zpackage")
file(WRITE "${base}/consumer/Dependencies/corrupt.zpackage" "not a package")
execute_process(COMMAND "${BIN}" run "${base}/consumer/Main.zsharp" RESULT_VARIABLE result ERROR_VARIABLE error TIMEOUT 10)
if(result EQUAL 0 OR error MATCHES "downloading dependency")
    message(FATAL_ERROR "corrupt local dependency did not fail without download: ${error}")
endif()
file(REMOVE "${base}/consumer/Dependencies/corrupt.zpackage")

# A packed consumer carries installed source, rather than requiring network.
command(package pack "${base}/consumer" Consumer)
file(WRITE "${base}/consumer/Helper.zsharp" "zsharp = type.script\nnoticed room Helper[] ( noticed brain Ping[] ( Print(\"CONSUMER HELPER ONLY\"): ) )\n")
file(WRITE "${base}/consumer/Own.zsharp" "zsharp = type.script\nnoticed room Own[] (\n import test_consumer.Helper():\n noticed brain Start[] ( Function.call(Helper:Helper:Ping): )\n)\n")
command(run "${base}/consumer/Own.zsharp")
if(NOT last_output MATCHES "CONSUMER HELPER ONLY" OR last_output MATCHES "DEPENDENCY INTERNAL CALL")
    message(FATAL_ERROR "consumer and dependency source names were not isolated: ${last_output}")
endif()

# Package/open a real game carrying its dependency without local archives.
if(WIN32)
file(MAKE_DIRECTORY "${base}/game/Dependencies")
file(COPY "${ROOT}/tests/game_package/" DESTINATION "${base}/game")
file(READ "${base}/game/project.zsettings" game_settings)
string(REPLACE "Dependencies (" "Dependencies (\n test_library:1.0.0.0:" game_settings "${game_settings}")
string(REPLACE "ZSharp: [1.0.2.1]:" "ZSharp: [1.2.1.0]:" game_settings "${game_settings}")
file(WRITE "${base}/game/project.zsettings" "${game_settings}")
file(READ "${base}/game/Main.zsharp" game_source)
string(REPLACE "noticed room Game[] (" "noticed room Game[] (\n import test_library.Main():" game_source "${game_source}")
string(REPLACE "Print(\"game start ran\"):" "Print(\"game start ran\"):\n Function.call(test_library:Main:Library:Hello [\"PACKAGED GAME\"]):\n Application.Quit:" game_source "${game_source}")
file(WRITE "${base}/game/Main.zsharp" "${game_source}")
file(COPY_FILE "${base}/library/Packages/Library.zpackage" "${base}/game/Dependencies/Library.zpackage")
command(package game "${base}/game" DependencyGame --unbytecode)
set(ENV{ZSHARP_PACKAGE_CACHE} "${base}/game-cache")
set(ENV{ZSHARP_PACKAGE_REGISTRY} "${base}/game-registry.json")
set(ENV{ZSHARP_PROJECT_REGISTRY} "${base}/project-registry.json")
set(ENV{ZSHARP_PLAY_STATS_REGISTRY} "${base}/playtime.json")
set(ENV{ZSHARP_SHORTCUT_CACHE} "${base}/shortcuts")
set(ENV{ZSHARP_DESKTOP_DIRECTORY} "${base}/desktop")
set(ENV{ZSHARP_SKIP_DESKTOP_INTEGRATION} 1)
set(ENV{ZSHARP_GAME_RASTER_TEST} 1)
set(ENV{ZSHARP_GAME_AUTOCLOSE_MS} 400)
file(WRITE "${base}/quit-input.txt" "n\n")
execute_process(COMMAND "${BIN}" run "${base}/game/Packages/DependencyGame.zgame"
    INPUT_FILE "${base}/quit-input.txt"
    RESULT_VARIABLE game_result OUTPUT_VARIABLE game_output ERROR_VARIABLE game_error TIMEOUT 12)
if(NOT game_result EQUAL 0 OR NOT game_output MATCHES "DEPENDENCY HELLO PACKAGED GAME" OR
   game_output MATCHES "MUST NOT AUTORUN" OR game_error MATCHES "downloading dependency")
    message(FATAL_ERROR "packaged game dependency failed: ${game_result}\n${game_output}\n${game_error}")
endif()
execute_process(COMMAND "${BIN}" run "${base}/game/Packages/DependencyGame-unbytecoded.zgame"
    INPUT_FILE "${base}/quit-input.txt"
    RESULT_VARIABLE game_result OUTPUT_VARIABLE game_output ERROR_VARIABLE game_error TIMEOUT 12)
if(NOT game_result EQUAL 0 OR NOT game_output MATCHES "DEPENDENCY HELLO PACKAGED GAME" OR
   game_output MATCHES "MUST NOT AUTORUN" OR game_error MATCHES "downloading dependency")
    message(FATAL_ERROR "source packaged game dependency failed: ${game_result}\n${game_output}\n${game_error}")
endif()
endif()

# Transitive sources included inside a pack must work without downloading.
file(MAKE_DIRECTORY "${base}/middle/Dependencies" "${base}/outer/Dependencies")
settings("${base}/middle" "test_middle" " test_library:1.0.0.0:")
settings("${base}/outer" "test_outer" " test_middle:1.0.0.0:")
file(COPY_FILE "${base}/library/Packages/Library.zpackage" "${base}/middle/Dependencies/Library.zpackage")
file(WRITE "${base}/middle/Relay.zsharp" "zsharp = type.script\nnoticed room Relay[] (\n import test_library.Main():\n noticed brain Hello[] ( Function.call(test_library:Main:Library:Hello [\"TRANSITIVE\"]): )\n)\n")
command(package pack "${base}/middle" Middle)
file(COPY_FILE "${base}/middle/Packages/Middle.zpackage" "${base}/outer/Dependencies/Middle.zpackage")
file(WRITE "${base}/outer/Main.zsharp" "zsharp = type.script\nnoticed room Main[] (\n import test_middle.Relay():\n noticed brain Start[] ( Function.call(test_middle:Relay:Relay:Hello): )\n)\n")
command(run "${base}/outer/Main.zsharp")
if(NOT last_output MATCHES "DEPENDENCY HELLO TRANSITIVE" OR last_error MATCHES "downloading dependency")
    message(FATAL_ERROR "transitive dependency failed: ${last_output}\n${last_error}")
endif()

if(EXISTS "${OUT}/c-project/C/Utilities.zc.dll" OR EXISTS "${OUT}/c-project/C/Utilities.zc.so" OR
   EXISTS "${OUT}/c-project/C/Utilities.zc.dylib")
    command(package pack "${OUT}/c-project" CUtilities)
    file(MAKE_DIRECTORY "${base}/c-consumer/Dependencies")
    settings("${base}/c-consumer" "test_c_consumer" " c_test:1.2.0.0:")
    file(COPY_FILE "${OUT}/c-project/Packages/CUtilities.zpackage" "${base}/c-consumer/Dependencies/Utilities.zpackage")
    file(WRITE "${base}/c-consumer/Main.zsharp" "zsharp = type.script\nnoticed room Main[] (\n import c:c_test.C.Utilities():\n noticed brain Start[] (\n number Sum = NativeSum(20, 22):\n Print(Sum):\n if[Discord.Client] ( Print(\"DEPENDENCY C SYNTAX\"): )\n move \"Bot\" to \"Hub\":\n text Callback = \"c:c_test.C.Utilities:add\":\n number Total = Function.call(Callback [20, 23]):\n Print(Total):\n )\n)\n")
    command(run "${base}/c-consumer/Main.zsharp")
    if(NOT last_output MATCHES "DEPENDENCY C SYNTAX" OR NOT last_output MATCHES "42" OR NOT last_output MATCHES "43")
        message(FATAL_ERROR "dependency C syntax did not load before parsing: ${last_output}\n${last_error}")
    endif()
endif()

# Reject cycles even when their source directories were already installed.
set(cycle_library "${base}/outer/Dependencies/test_middle/1.0.0.0/Dependencies/test_library/1.0.0.0")
settings("${cycle_library}" "test_library" " test_outer:1.0.0.0:")
file(MAKE_DIRECTORY "${cycle_library}/Dependencies/test_outer/1.0.0.0")
settings("${cycle_library}/Dependencies/test_outer/1.0.0.0" "test_outer" "")
file(WRITE "${cycle_library}/Dependencies/test_outer/1.0.0.0/.zsharp-dependency-complete"
    "0000000000000000000000000000000000000000000000000000000000000000")
execute_process(COMMAND "${BIN}" run "${base}/outer/Main.zsharp"
    RESULT_VARIABLE result ERROR_VARIABLE error TIMEOUT 10)
if(result EQUAL 0 OR NOT error MATCHES "cyclic dependency")
    message(FATAL_ERROR "cyclic dependencies were not rejected: ${error}")
endif()

# Optional live endpoint check; kept out of offline CI.
if(DEFINED STORE_FAILURE_TEST AND STORE_FAILURE_TEST)
    file(MAKE_DIRECTORY "${base}/store-failure")
    settings("${base}/store-failure" "store_failure" " discordz:1.0.0.0:")
    file(WRITE "${base}/store-failure/Main.zsharp" "zsharp = type.script\nnoticed room Main[] ( noticed brain Start[] ( Print(\"MUST NOT RUN\"): ) )\n")
    execute_process(COMMAND "${BIN}" run "${base}/store-failure/Main.zsharp"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
    if(result EQUAL 0 OR output MATCHES "MUST NOT RUN" OR
       NOT error MATCHES "downloading dependency discordz:1.0.0.0" OR
       NOT error MATCHES "could not securely download" OR
       EXISTS "${base}/store-failure/Dependencies/discordz-1.0.0.0.zpackage.tmp")
        message(FATAL_ERROR "failed Store download did not fail safely: ${result}\n${output}\n${error}")
    endif()
    message(STATUS "Live Store failure handled before script execution without a partial archive")
endif()
message(STATUS "Source dependencies: local precedence, source-only packs, bot run, Lua, internal calls, bytecode and validation passed")
