set(project "${OUT}/package-validation-cache")
file(MAKE_DIRECTORY "${project}")
file(COPY "${ROOT}/tests/game_instances/" DESTINATION "${project}")
set(ENV{ZSHARP_SKIP_UPDATE_CHECK} "1")
set(ENV{ZSHARP_PACKAGE_PROFILE} "1")
file(READ "${project}/Floor1.zscene" scene)
set(placements "")
foreach(i RANGE 1 1200)
 string(APPEND placements "{\"id\":\"Cube\",\"name\":\"Stress${i}\",\"location\":{\"x\":${i},\"y\":0,\"z\":0}},\n")
endforeach()
string(REPLACE "  [" "  [\n${placements}" scene "${scene}")
file(WRITE "${project}/Floor1.zscene" "${scene}")
set(script "zsharp = type.script\nnoticed room Stress[] (\n noticed brain Inspect[] (\n")
foreach(i RANGE 1 160)
 string(APPEND script "number Sample${i} = Floor1.LeftDoor.positionX:\n")
endforeach()
string(APPEND script ")\n)\n")
file(WRITE "${project}/Stress.zsharp" "${script}")
function(package_ok name)
 execute_process(COMMAND "${BIN}" package game "${project}" "${name}" ${ARGN}
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
 if(NOT status EQUAL 0)
  message(FATAL_ERROR "Packaging failed: ${output}\n${error}")
 endif()
 string(REGEX MATCHALL "game model loads=1" model_loads "${error}")
 list(LENGTH model_loads count)
 if(NOT count EQUAL EXPECTED_LOADS OR error MATCHES "game model loads=[2-9]")
  message(FATAL_ERROR "Scene model reloaded unexpectedly: ${error}")
 endif()
endfunction()
set(EXPECTED_LOADS 1)
package_ok(First)
package_ok(Repeat)
file(SHA256 "${project}/Packages/First.zgame" first)
file(SHA256 "${project}/Packages/Repeat.zgame" second)
if(NOT first STREQUAL second)
 message(FATAL_ERROR "Validation reuse changed deterministic package contents")
endif()
set(EXPECTED_LOADS 2)
package_ok(Source --unbytecode)
# A new packaging operation must never reuse a previous build's model.
string(REPLACE "\"x\": 100" "\"x\": 101" changed "${scene}")
file(WRITE "${project}/Floor1.zscene" "${changed}")
set(EXPECTED_LOADS 1)
package_ok(Changed)
file(SHA256 "${project}/Packages/Changed.zgame" changed_hash)
if(first STREQUAL changed_hash)
 message(FATAL_ERROR "Changed scene was not included in package")
endif()
# instanceId comes after location in the placement grammar.
string(REPLACE "\"x\":1,\"y\":0,\"z\":0}" "\"x\":1,\"y\":0,\"z\":0},\"instanceId\":\"bad.identifier\"" invalid "${scene}")
file(WRITE "${project}/Floor1.zscene" "${invalid}")
execute_process(COMMAND "${BIN}" package game "${project}" Invalid
 RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
if(status EQUAL 0 OR NOT error MATCHES "invalid instanceId")
 message(FATAL_ERROR "Invalid unreferenced placement escaped validation: ${output}\n${error}")
endif()
file(WRITE "${project}/Floor1.zscene" "${scene}")
string(REPLACE "LeftDoor.positionX" "MissingDoor.positionX" bad_script "${script}")
file(WRITE "${project}/Stress.zsharp" "${bad_script}")
execute_process(COMMAND "${BIN}" package game "${project}" InvalidProperty
 RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
if(status EQUAL 0 OR NOT error MATCHES "unknown.*instance")
 message(FATAL_ERROR "Unknown placement escaped validation: ${output}\n${error}")
endif()
