#ifndef ZSHARP_H
#define ZSHARP_H

#define ZSHARP_VERSION_MAJOR 1
#define ZSHARP_VERSION_MINOR 0
#define ZSHARP_VERSION_PATCH 2
#define ZSHARP_VERSION_REVISION 4
#define ZSHARP_SOURCE_EXTENSION ".zsharp"
#define ZSHARP_SCENE_EXTENSION ".zscene"
#define ZSHARP_OBJECT_EXTENSION ".zobject"
#define ZSHARP_AUDIO_EXTENSION ".zaudio"
#define ZSHARP_STYLE_EXTENSION ".zss"

#endif
